#:schema node_modules/wrangler/config-schema.json

name = "nachrichten-blog"
main = "./src/index.ts"
compatibility_date = "2026-08-23"

[vars]
GITHUB_REPO_PRIVATE = "0"
GITHUB_APP_INSTALLATION_ID = "155931215"

[assets]
directory = "./_site"
binding = "ASSETS"
run_worker_first = true
